name: Saham App
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy Saham App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p ~/saham-app/ # create a new folder
            cd ~/saham-app/ # navigate into the folder
            git clone https://github.com/fgprayogo/sahamapp.git # clone the repo into the 'app' folder
            cd sahamapp # navigate into the repo
            npm install # install dependencies 
            pm2 start server.js # start as a background service.
