name: Saham App
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy Saham App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p ~/saham-app/ # create a new folder
            cd ~/saham-app/ # navigate into the folder
            git pull https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/fgprayogo/sahamapp.git
            npm install # install dependencies 
            pm2 start server.js # start as a background service.
